export interface IORFile {
        dateFileReceived: string,
        orDataFileGroupID: number,
        providerID: string,
        providerKey: number,
        clientName: string,
        beginDateRange: string,
        endDateRange: string,
        fileType_SubsystemDetailType: string,
        fileType: string,
        fileTypeKey: number,
        subsystemDetailType: string,
        subsystemDetailTypeKey: number,
        rowCountPrep: number,
        rowCountExpected: number,
        rowCountConverted: number,
        processStep: string,
        processStatus: string,
        pduJobNumber: number,
        publishCompleteDate: string,
        errorMessage: string,
        retryCount: number,
        rawFilename: string
}


/*export interface IORFile {
        jsxid: number,
        ORDataFileGroupID:string,
        PDUJobNumber: string,
        beginDtRange: string,
        endDtRange: string,
        clientNm: string,
        providerID: string,
        fileType: string,
        subsystemDetailType: string,
        dtFileReceived : string,
        rawFilename: string,
        pubCompleteDt: string,
        stepNm:string,
        statusNm: string,
        errMsg: string,
        rowCntConverted: string,
        rowCntExpected: string,
        retryCnt: number,
        retryFl: number,
        utilityCd: string
}*/